### PR TITLE
Add docker quickstart

### PR DESCRIPTION
**Pull request by fearnworks**
- Add Dockerfile and run_docker script
- Add Entrypoint script for easy hello world inference
- Update quick start section of readme
- Add .env file template for passing in hf api token to docker runtime

### CODE REVIEW

**Comment by fearnworks** [comment]
Next item I am looking at here is to set up some way to persist model downloads across runs. I've used a mounted volume solution in the past for this with docker compose. That should cut down consecutive sessions with the container down significantly.

**Comment by lpietrobon** [comment]
@fearnworks is this to replace the `sh setup_moe.sh` setup currently suggested in the README?

**Comment by fearnworks** [comment]
> @fearnworks is this to replace the `sh setup_moe.sh` setup currently suggested in the README?

This is an additional option to run the project inside of a container instead of directly in your local environment. It actually utilizes the setup_moe.sh as part of its image build process.

**Comment by fearnworks** [comment]
I am likely going to close this pull, I have extended this to include docker compose and the webui cli option in the ui branch.

**Pull request closed without merging**
